# Generated by Django 4.2.7 on 2025-09-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='inventory_a_timesta_70855e_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='inventory_a_user_id_c1aff7_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='inventory_a_model_n_261f0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='inventory_a_status_aa0ee1_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='inventory_a_serial__77797e_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='inventory_a_purchas_752e8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='inventory_a_status_898764_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='inventory_a_created_a5ad85_idx',
        ),
    ]
